services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: user
      POSTGRES_DB: db1
#  es:
#    image: elasticsearch:8.11.0
#    ports:
#      - "9200:9200"
#      - "9300:9300"
#    environment:
#      discovery.type: single-node
#      xpack.security.enabled: false
  rq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
#    restart: unless-stopped

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    command: [ "--config=/etc/otel-collector-config.yaml" ]
    volumes:
      - ./monitoring-conf/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"   # OTLP gRPC receiver
      - "4318:4318"   # OTLP HTTP receiver
      - "8889:8889"   # Prometheus metrics
    depends_on:
      - prometheus
      - loki
    networks:
      - app-net

  grafana:
    image: grafana/grafana:latest
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./monitoring-conf/grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
#      - ./grafana/data:/var/lib/grafana
    networks:
      - app-net

  loki:
    image: grafana/loki:latest
    restart: always
    ports:
      - "3100:3100"
      - "9096:9096"   # OTLP gRPC 포트 추가!
    command:
      - -config.file=/etc/loki/loki-config.yaml
      - -validation.allow-structured-metadata=true
    volumes:
      - ./monitoring-conf/loki-config.yaml:/etc/loki/loki-config.yaml
      - ./monitoring/loki:/loki
    networks:
      - app-net

    # Prometheus (Metrics)
  prometheus:
    image: prom/prometheus:latest
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.retention.time=7d'           # 7일 보관
      - '--storage.tsdb.retention.size=2GB'          # 2GB 제한
      - '--web.enable-remote-write-receiver'
    volumes:
      - ./monitoring-conf/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./monitoring/prometheus:/prometheus
    ports:
      - "9090:9090"
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '1.0'
    networks:
      - app-net

networks:
  app-net:
    external: true