spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sideproject
    username: root
    password: skybmw!004
    driver-class-name: com.mysql.cj.jdbc.Driver 

  jwt:
    secret:
      key: "c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppd29vbi1zcHJpbmctYm9vdC1zZWN1cml0eS1qd3QtdHV0b3JpYWwK"