receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
      http:
        endpoint: 0.0.0.0:4318

processors:
  batch:  # 개별 매트릭 데이터를 배치로 묶어 처리 효율성 증가, 일정 기간에 데이터가 모이면 즉시 배치 전송
    timeout: 1s
    send_batch_size: 1024
  memory_limiter: # 메모리 사용량 제한
    limit_mib: 512
    check_interval: 1s  # 1초마다 메모리 사용량 확인

exporters:
  prometheusremotewrite:
    endpoint: http://prometheus:9090/api/v1/write
    timeout: 30s  # ← 최상위에 바로

    # Retry 설정
    retry_on_failure:
      enabled: true
      initial_interval: 5s
      max_interval: 30s
      max_elapsed_time: 300s

    # 압축 (선택)
    compression: snappy

    # Resource attributes를 label로 변환
    resource_to_telemetry_conversion:
      enabled: true

  otlphttp/logs:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

  debug:
    verbosity: detailed
    sampling_initial: 5          # 처음 5개는 상세 출력
    sampling_thereafter: 200     # 이후 200개당 1개만 출력

service:
  pipelines:
    logs:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [otlphttp/logs, debug]

    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheusremotewrite, debug]