### 로그인 요청
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
  "id": "test",
  "password": "password123"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
    client.global.set("refreshToken", response.body.data.refreshToken);
%}