### 알림 확인
GET http://localhost:8080/api/v1/notifications
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 알림 읽음 처리
PUT http://localhost:8080/api/v1/notifications/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### 알림 삭제
DELETE http://localhost:8080/api/v1/notifications/1
Content-Type: application/json
Authorization: Bearer {{accessToken}}
