### PR 게시글 작성
POST {{host}}/api/v1/post/pr
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "pr 타이틀",
  "introduce": "안녕하세요! 사이드 프로젝트하고 싶어요! 여기 제 이력 좀 보세요 개쩌는 프로젝트 엄청난 수상경력 간지나는 학력 첨부 이미지는 제 포트폴리오의 일부입니다! 관심있으시면 채팅주세요~",
  "position": "BACKEND",
  "workType": "ALL",
  "documentUrl": ["http://pr-file", "http://pr-file2"],
  "experiences": [{
    "title": "사이드 프로젝트1",
    "description": "이러이러한 사이드 프로젝트에요~",
    "startDate": "2025-02-05T13:53:31",
    "endDate": "2025-03-05T13:53:31",
    "documentUrl": "http://pr-experience-file",
    "teamSize": 5
  }],
  "techStacks": [{
    "id": 1,
    "level": 1
  },{
    "id": 12,
    "level": 5
  }]
}

### PR 게시글 리스트 조회
GET {{host}}/api/v1/post/pr
Content-Type: application/json

### PR 게시글 리스트 조회
GET {{host}}/api/v1/post/pr?page=0&size=20&workTypes=OFFLINE&positions=FRONTEND,BACKEND&techStackIds=1
Content-Type: application/json

### PR 게시글 조회
GET {{host}}/api/v1/post/pr/2
Content-Type: application/json

### PR 게시글 수정
PUT {{host}}/api/v1/post/pr/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "title": "pr 타이틀222",
  "introduce": "소개 글 업데이트",
  "position": "FRONTEND",
  "workType": "OFFLINE",
  "documentUrl": ["http://pr-file1", "http://pr-file2"],
  "experiences": [{
    "title": "사이드 프로젝트1",
    "description": "이러이러한 사이드 프로젝트에요~",
    "startDate": "2025-02-05T13:53:31",
    "endDate": "2025-03-05T13:53:31",
    "documentUrl": "http://pr-experience-file",
    "teamSize": 5
  },{
    "title": "사이드 프로젝트2",
    "description": "플젝222222",
    "startDate": "2025-03-05T13:53:31",
    "endDate": "2025-04-05T13:53:31",
    "documentUrl": "http://pr-experience2-file",
    "teamSize": 1
  }],
  "techStacks": [{
    "id": 1,
    "level": 1
  },{
    "id": 16,
    "level": 10
  }]
}

### PR 게시글 삭제
DELETE {{host}}/api/v1/post/pr/3
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### PR 댓글 작성
POST {{host}}/api/v1/prs/2/comments
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "댓글4"
}

### PR 댓글 조회
GET {{host}}/api/v1/prs/2/comments
Content-Type: application/json

### PR 댓글 수정
PUT {{host}}/api/v1/prs/2/comments/2
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "content": "댓글2 수정"
}

### PR 댓글 삭제
DELETE {{host}}/api/v1/prs/comment/40
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### PR 대댓글 조회
GET {{host}}/api/v1/prs/comment/5/reply
Content-Type: application/json

### PR 대댓글 작성
POST {{host}}/api/v1/prs/2/comment
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "parentId": 5,
  "content": "대댓글10-2"
}
